name: core
description: Flutter Core App for iupp.
version: 1.0.1
publish_to: none
author:
homepage:

environment:
 sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
